---
title: "Tijerina_L1"
output: html_document
date: "2025-07-14"
---
# load package
library(arrow)
library(dplyr)
library(ggplot2)

# load data
merged_data <- read_parquet(file = "merged_data.parquet" , stringsAsFactors = TRUE)

# look at top of data
head(merged_data[, 1:10], 6) #show the first 6 rows, 10 first columns

# look at bottom of data
tail(merged_data[,1:10], 6) #show the last 6 rows, 10 first columns

# structure and variability types
str(merged_data[,1:10]) #show structure and variable types, 10 first columns

# cleaning data
merged_data <- na.omit(merged_data)

# load it back in
merged_data <- read_parquet(file = "merged_data.parquet", stringsAsFactors = TRUE)

# subsetting data
subset_data_az <- subset(merged_data, STATE_ABBR_2010SVI == "AZ")

# summarize data
summary(subset_data_az[, 1:10], 6)

# create summaries for subset
upward_mean_2010_az <- mean(subset_data_az$upward_mobility_rate_2010)
upward_sd_2010_az <- sd(subset_data_az$upward_mobility_rate_2010)
upward_mean_2020_az <- mean(subset_data_az$upward_mobility_rate_2020)
upward_sd_2020_az <- sd(subset_data_az$upward_mobility_rate_2020)

# print mean AZ
print(upward_mean_2010_az)

# print mean CA
subset_data_ca <- subset(merged_data, STATE_ABBR_2010SVI == "CA")
print(upward_mean_2010_ca <- mean(subset_data_ca$upward_mobility_rate_2010))

# county level summary
# pima upward mean
print(pima_upward_mean_2010_az <- mean(subset_data_az$upward_mobility_rate_2010[subset_data_az$COUNTY_2010SVI == "Pima County"]))
# pima upward sd
print(pima_upward_sd_2010_az <- sd(subset_data_az$upward_mobility_rate_2010[subset_data_az$COUNTY_2010SVI == "Pima County"]))
# del norte upward mean
print(delnorte_upward_mean_2010_ca <- mean(subset_data_ca$upward_mobility_rate_2010[subset_data_ca$COUNTY_2010SVI == "Del Norte County"]))
# del norte upward sd
print(delnorte_upward_sd_2010_ca <- sd(subset_data_ca$upward_mobility_rate_2010[subset_data_ca$COUNTY_2010SVI == "Del Norte County"]))

# summary stats using dplyr
#  install 
# summarize upward mobility by county in AZ
summary_stats_upward_2010 <- subset_data_az %>%
  group_by(COUNTY_2010SVI) %>%
  summarize(mean_mobility_2010_az = mean(upward_mobility_rate_2010),
            sd_mobility_2010_az = sd(upward_mobility_rate_2010))
# view result
(head(summary_stats_upward_2010))

# visualization with ggplot2
mobility_plot_sumstats <- ggplot(data = summary_stats_upward_2010,
                        mapping = aes(x= COUNTY_2010SVI, y=mean_mobility_2010_az)) + geom_boxplot()
# print mobility plot
print(mobility_plot_sumstats)

# state and county summary
summary_stats_upward_2010_all <- merged_data %>%
  group_by(STATE_ABBR_2010SVI, COUNTY_2010SVI) %>%
  summarize(mean_mobility_2010 = mean(upward_mobility_rate_2010), sd_mobility_2010 = sd(upward_mobility_rate_2010))
# grouping by state
mobility_plot_by_state_upward <- ggplot(data = summary_stats_upward_2010_all, mapping = aes(x = STATE_ABBR_2010SVI, y = mean_mobility_2010)) + geom_boxplot()
print(mobility_plot_by_state_upward)

# remove missing states
summary_stats_upward_2010_all <- summary_stats_upward_2010_all[!is.na(summary_stats_upward_2010_all$STATE_ABBR_2010SVI),]

# group by state
mobility_plot_sum_by_state <- ggplot(data = summary_stats_upward_2010_all, mapping = aes(x= STATE_ABBR_2010SVI, y=mean_mobility_2010, fill = STATE_ABBR_2010SVI)) + geom_boxplot()
print(mobility_plot_sum_by_state)
# save plot
ggsave(plot = mobility_plot_sum_by_state, filename = "output/mobility_plot_sum_by_state-2010.pdf")

# student activities

# Maricopa County SD
#   2010
print(maricopa_upward_sd_2010_az <- sd(subset_data_az$upward_mobility_rate_2010[subset_data_az$COUNTY_2010SVI == "Maricopa County"]))
print(mobility_plot)
#   2020
print(maricopa_upward_sd_2020_az <- sd(subset_data_az$upward_mobility_rate_2020[subset_data_az$COUNTY_2020SVI == "Maricopa County"]))
print(mobility_plot)

# Maricopa County Mean
#   2010
print(maricopa_upward_mean_2010_az <- mean(subset_data_az$upward_mobility_rate_2010[subset_data_az$COUNTY_2010SVI == "Maricopa County"]))
#   2020
print(maricopa_upward_mean_2020_az <- mean(subset_data_az$upward_mobility_rate_2020[subset_data_az$COUNTY_2020SVI == "Maricopa County"]))

# Alameda County SD
# 2010
print(alameda_upward_sd_2010_ca <- sd(subset_data_ca$upward_mobility_rate_2010[subset_data_ca$COUNTY_2010SVI == "Alameda County"]))
# 2020
print(alameda_upward_sd_2020_ca <- sd(subset_data_ca$upward_mobility_rate_2020[subset_data_ca$COUNTY_2020SVI == "Alameda County"]))
# Alameda County Mean
#   2010
print(alameda_upward_mean_2010_ca <- mean(subset_data_ca$upward_mobility_rate_2010[subset_data_ca$COUNTY_2010SVI == "Alameda County"]))
print(mobility_plot)
#   2020
print(alameda_upward_mean_2020_ca <- mean(subset_data_ca$upward_mobility_rate_2020[subset_data_ca$COUNTY_2020SVI == "Alameda County"]))
print(mobility_plot)

#   Boxplot Selected County

#   Maricopa
#     2010

#     2020

#   Alameda
#     2010

#     2020